name: Generate Helm Chart Documentation 
on:
  push:
jobs:
  generate-helm-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Aimee-888/HelmDocs-GithubAction@v1
        with: 
          # provide list of dirs to run helm-docs on, seperate by comma without a space
          src_path: sample_charts,sample_charts2
          template_file: README.md.gotmpl
          # provide name of dirs to ignore, seperate by comma without a space
          ignored_dirs: dir1,dir2
          commit_message: my custom commit message
          username: sample-username
          email: sample@mail.com
          git_push: true 

